load("@rules_python//python:defs.bzl", "py_binary")

py_library(
    name = "smu_utils_lib",
    srcs = [
        "smu_utils_lib.py",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//smu:dataset_pb2",
    ],
)
